# -*- coding: utf-8 -*-
"""coca_cola_financial_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gS4633QaXksz88wvd9ivq2HoBkSHbjC7
"""

import pandas as pd

folder_path = '/content/drive/MyDrive/CokeCsv/'

income = pd.read_csv(folder_path + 'income_statement.csv')
balance = pd.read_csv(folder_path + 'balance_sheet.csv')
cashflow = pd.read_csv(folder_path + 'cash_flow.csv')

print(income.head(3), "\n")
print(balance.head(3), "\n")
print(cashflow.head(3))

income['Year'] = income['Year'].astype(str)

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid')  # arka plan çizgili

plt.figure(figsize=(10,6))  # grafik boyutu

plt.plot(income['Year'], income['Total Revenue'], marker='o', label='Total Revenue')
plt.plot(income['Year'], income['Net Income'], marker='o', label='Net Income')

plt.title('Income Statement: Revenue & Net Income Trend')
plt.xlabel('Year')
plt.ylabel('USD')
plt.legend()
plt.show()

# Year sütununu string yapalım (grafik için)
balance['Year'] = balance['Year'].astype(str)

plt.figure(figsize=(10,6))

plt.plot(balance['Year'], balance['Total Assets'], marker='o', label='Total Assets')
plt.plot(balance['Year'], balance['Total Liabilities'], marker='o', label='Total Liabilities')
plt.plot(balance['Year'], balance['Total Equity'], marker='o', label='Total Equity')

plt.title('Balance Sheet: Assets, Liabilities & Equity')
plt.xlabel('Year')
plt.ylabel('USD')
plt.legend()
plt.show()

# Year sütununu string yapalım
cashflow['Year'] = cashflow['Year'].astype(str)

plt.figure(figsize=(10,6))

plt.plot(cashflow['Year'], cashflow['Operating Cash Flow'], marker='o', label='Operating Cash Flow')
plt.plot(cashflow['Year'], cashflow['Investing Cash Flow'], marker='o', label='Investing Cash Flow')
plt.plot(cashflow['Year'], cashflow['Financing Cash Flow'], marker='o', label='Financing Cash Flow')

plt.title('Cash Flow Statement')
plt.xlabel('Year')
plt.ylabel('USD')
plt.legend()
plt.show()

income['Profit Margin'] = income['Net Income'] / income['Total Revenue']

print(income[['Year','Total Revenue','Net Income','Profit Margin']])

plt.figure(figsize=(10,6))

plt.plot(income['Year'], income['Profit Margin'], marker='o')

plt.title('Profit Margin Trend')
plt.xlabel('Year')
plt.ylabel('Profit Margin')

plt.show()

balance['Debt Ratio'] = balance['Total Liabilities'] / balance['Total Assets']

print(balance[['Year','Debt Ratio']])

plt.figure(figsize=(10,6))

plt.plot(balance['Year'], balance['Debt Ratio'], marker='o')

plt.title('Debt Ratio Trend')
plt.xlabel('Year')
plt.ylabel('Debt Ratio')

plt.show()

cashflow['Free Cash Flow'] = cashflow['Operating Cash Flow'] - cashflow['Investing Cash Flow']

print(cashflow[['Year','Free Cash Flow']])

plt.figure(figsize=(10,6))

plt.plot(cashflow['Year'], cashflow['Free Cash Flow'], marker='o')

plt.title('Free Cash Flow Trend')
plt.xlabel('Year')
plt.ylabel('Free Cash Flow')

plt.show()

income[['Total Revenue','Net Income']].corr()

# Financial Ratios hesaplama

income['Profit Margin'] = income['Net Income'] / income['Total Revenue']

balance['Debt Ratio'] = balance['Total Liabilities'] / balance['Total Assets']

cashflow['Free Cash Flow'] = cashflow['Operating Cash Flow'] - cashflow['Investing Cash Flow']

financial_summary = pd.DataFrame()

financial_summary['Year'] = income['Year']
financial_summary['Revenue'] = income['Total Revenue']
financial_summary['Net Income'] = income['Net Income']
financial_summary['Profit Margin'] = income['Profit Margin']
financial_summary['Debt Ratio'] = balance['Debt Ratio']
financial_summary['Free Cash Flow'] = cashflow['Free Cash Flow']

print(financial_summary)

plt.figure(figsize=(10,6))

plt.plot(financial_summary['Year'], financial_summary['Profit Margin'], marker='o', label='Profit Margin')
plt.plot(financial_summary['Year'], financial_summary['Debt Ratio'], marker='o', label='Debt Ratio')

plt.title('Financial Ratio Analysis')
plt.xlabel('Year')
plt.ylabel('Ratio')

plt.legend()
plt.show()

plt.figure(figsize=(10,6))

plt.plot(financial_summary['Year'], financial_summary['Free Cash Flow'], marker='o')

plt.title('Free Cash Flow Trend')
plt.xlabel('Year')
plt.ylabel('USD')

plt.show()

correlation = financial_summary.drop(columns=['Year']).corr()

print(correlation)

plt.figure(figsize=(8,6))

sns.heatmap(correlation, annot=True)

plt.title('Financial Data Correlation Heatmap')

plt.show()

plt.figure(figsize=(10,6))

plt.plot(financial_summary['Year'], financial_summary['Revenue'], marker='o', label='Revenue')
plt.plot(financial_summary['Year'], financial_summary['Net Income'], marker='o', label='Net Income')

plt.title('Revenue vs Net Income')
plt.xlabel('Year')
plt.ylabel('USD')

plt.legend()

plt.savefig('revenue_net_income.png')

plt.show()

# Missing values kontrolü
print(income.isnull().sum())
print(balance.isnull().sum())
print(cashflow.isnull().sum())

# Veri tipleri
print(income.dtypes)
print(balance.dtypes)
print(cashflow.dtypes)

income['Revenue Growth'] = income['Total Revenue'].pct_change()

plt.figure(figsize=(10,6))
plt.plot(income['Year'], income['Revenue Growth'], marker='o')
plt.title('Revenue Growth Rate')
plt.xlabel('Year')
plt.ylabel('Growth Rate')
plt.show()

financial_summary['ROE'] = financial_summary['Net Income'] / balance['Total Equity']

plt.figure(figsize=(10,6))
plt.plot(financial_summary['Year'], financial_summary['ROE'], marker='o')

plt.title('Return on Equity (ROE)')
plt.xlabel('Year')
plt.ylabel('ROE')

plt.show()

financial_summary['Asset Turnover'] = financial_summary['Revenue'] / balance['Total Assets']

plt.figure(figsize=(10,6))
plt.plot(financial_summary['Year'], financial_summary['Asset Turnover'], marker='o')

plt.title('Asset Turnover Ratio')
plt.xlabel('Year')
plt.ylabel('Ratio')

plt.show()

plt.figure(figsize=(10,6))

plt.bar(financial_summary['Year'], financial_summary['Revenue'])

plt.title('Total Revenue by Year')
plt.xlabel('Year')
plt.ylabel('USD')

plt.show()

plt.figure(figsize=(8,6))

plt.scatter(financial_summary['Revenue'], financial_summary['Net Income'])

plt.xlabel('Revenue')
plt.ylabel('Net Income')

plt.title('Revenue vs Net Income Relationship')

plt.show()

from sklearn.linear_model import LinearRegression
import numpy as np

X = np.arange(len(income)).reshape(-1,1)
y = income['Total Revenue']

model = LinearRegression()
model.fit(X,y)

predicted = model.predict(X)

plt.figure(figsize=(10,6))
plt.plot(income['Year'], y, marker='o', label='Actual Revenue')
plt.plot(income['Year'], predicted, label='Trend Prediction')

plt.legend()
plt.title('Revenue Trend Prediction')

plt.show()

fig, axes = plt.subplots(2,2, figsize=(14,10))

axes[0,0].plot(financial_summary['Year'], financial_summary['Revenue'])
axes[0,0].set_title('Revenue')

axes[0,1].plot(financial_summary['Year'], financial_summary['Net Income'])
axes[0,1].set_title('Net Income')

axes[1,0].plot(financial_summary['Year'], financial_summary['Profit Margin'])
axes[1,0].set_title('Profit Margin')

axes[1,1].plot(financial_summary['Year'], financial_summary['Debt Ratio'])
axes[1,1].set_title('Debt Ratio')

plt.tight_layout()
plt.show()

financial_summary.to_csv("financial_analysis_summary.csv")

# --- CLEAN MERGED FINANCIAL DATASET ---

income['Year'] = income['Year'].astype(int)
balance['Year'] = balance['Year'].astype(int)
cashflow['Year'] = cashflow['Year'].astype(int)

financial_data = income.merge(balance, on="Year").merge(cashflow, on="Year")

print(financial_data.head())

# --- WARREN BUFFETT STYLE METRICS ---

financial_data['Profit Margin'] = financial_data['Net Income'] / financial_data['Total Revenue']
financial_data['ROE'] = financial_data['Net Income'] / financial_data['Total Equity']
financial_data['Debt Ratio'] = financial_data['Total Liabilities'] / financial_data['Total Assets']
financial_data['Free Cash Flow'] = financial_data['Operating Cash Flow'] - financial_data['Investing Cash Flow']

print("Average Profit Margin:", financial_data['Profit Margin'].mean())
print("Average ROE:", financial_data['ROE'].mean())
print("Average Debt Ratio:", financial_data['Debt Ratio'].mean())

# Buffett-style evaluation

if financial_data['ROE'].mean() > 0.15:
    print("Strong ROE (Buffett likes this)")

if financial_data['Debt Ratio'].mean() < 0.6:
    print("Healthy debt level")

if financial_data['Profit Margin'].mean() > 0.2:
    print("Strong pricing power")

# --- DISCOUNTED CASH FLOW MODEL ---

latest_fcf = financial_data['Free Cash Flow'].iloc[-1]

growth_rate = 0.05
discount_rate = 0.09
terminal_growth = 0.025
years = 5

future_values = []

for i in range(1, years+1):
    fcf = latest_fcf * (1 + growth_rate)**i
    discounted = fcf / (1 + discount_rate)**i
    future_values.append(discounted)

terminal_value = (future_values[-1] * (1 + terminal_growth)) / (discount_rate - terminal_growth)

terminal_discounted = terminal_value / ((1 + discount_rate)**years)

enterprise_value = sum(future_values) + terminal_discounted

print("Estimated Enterprise Value:", enterprise_value)

# --- PROFESSIONAL FINANCIAL DASHBOARD ---

fig, axes = plt.subplots(2,2, figsize=(16,10))

axes[0,0].plot(financial_data['Year'], financial_data['Total Revenue'])
axes[0,0].set_title("Revenue")

axes[0,1].plot(financial_data['Year'], financial_data['Net Income'])
axes[0,1].set_title("Net Income")

axes[1,0].plot(financial_data['Year'], financial_data['ROE'])
axes[1,0].set_title("Return on Equity")

axes[1,1].plot(financial_data['Year'], financial_data['Free Cash Flow'])
axes[1,1].set_title("Free Cash Flow")

plt.tight_layout()
plt.show()

# --- MACHINE LEARNING REVENUE FORECAST ---

from sklearn.linear_model import LinearRegression
import numpy as np

years_numeric = np.arange(len(financial_data)).reshape(-1,1)
revenue = financial_data['Total Revenue']

model = LinearRegression()
model.fit(years_numeric, revenue)

future_years = np.arange(len(financial_data), len(financial_data)+5).reshape(-1,1)

future_predictions = model.predict(future_years)

print("Future Revenue Forecast:")
print(future_predictions)

plt.figure(figsize=(10,6))

plt.plot(financial_data['Year'], revenue, marker='o', label="Historical Revenue")

future_year_labels = np.arange(financial_data['Year'].max()+1, financial_data['Year'].max()+6)

plt.plot(future_year_labels, future_predictions, marker='o', label="Forecast")

plt.legend()
plt.title("Revenue Forecast")
plt.xlabel("Year")
plt.ylabel("Revenue")

plt.show()

# --- INTERACTIVE FINANCIAL VISUALIZATION ---

import plotly.express as px

fig = px.line(
    financial_data,
    x="Year",
    y=["Total Revenue","Net Income"],
    title="Interactive Revenue vs Net Income"
)

fig.show()

# --- STOCK RISK ANALYSIS ---

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

tickers = ["KO","AAPL","MSFT","TSLA","AMZN"]
data = yf.download(tickers, start="2018-01-01")["Close"]

# 'stock' değişkeni tanımlanmadığı için 'data' DataFrame'inden bir hisse senedi seçmeliyiz.
# Örneğin, 'KO' (Coca-Cola) hissesini seçelim.
returns = data['KO'].pct_change().dropna()

annual_return = returns.mean() * 252
annual_volatility = returns.std() * (252 ** 0.5)

print("Annual Return:", annual_return)
print("Annual Volatility:", annual_volatility)

plt.figure(figsize=(10,6))

plt.hist(returns, bins=50)

plt.title("Distribution of Daily Returns")

plt.show()

# --- AUTOMATED FINANCIAL SUMMARY ---

print("----- FINANCIAL REPORT -----")

print("Average Revenue:", financial_data['Total Revenue'].mean())

print("Average Net Income:", financial_data['Net Income'].mean())

print("Average Profit Margin:", financial_data['Profit Margin'].mean())

print("Average ROE:", financial_data['ROE'].mean())

print("Average Free Cash Flow:", financial_data['Free Cash Flow'].mean())

print("Debt Ratio:", financial_data['Debt Ratio'].mean())

if financial_data['ROE'].mean() > 0.15:
    print("Company shows strong profitability.")

if financial_data['Free Cash Flow'].mean() > 0:
    print("Company generates healthy free cash flow.")

if financial_data['Debt Ratio'].mean() < 0.6:
    print("Debt levels appear manageable.")

# --- DOWNLOAD MULTIPLE STOCK DATA ---

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

tickers = ["KO","AAPL","MSFT","TSLA","AMZN"]

data = yf.download(tickers, start="2018-01-01")["Close"]

print(data.head())

# --- CALCULATE RETURNS ---

returns = data.pct_change().dropna()

print(returns.head())

# --- RISK & RETURN ANALYSIS ---

annual_returns = returns.mean() * 252
volatility = returns.std() * (252 ** 0.5)

summary = pd.DataFrame()

summary["Annual Return"] = annual_returns
summary["Volatility"] = volatility

print(summary)

# --- SHARPE RATIO ---

risk_free_rate = 0.02

sharpe = (annual_returns - risk_free_rate) / volatility

summary["Sharpe Ratio"] = sharpe

print(summary.sort_values("Sharpe Ratio", ascending=False))

# --- RISK RETURN SCATTER PLOT ---

plt.figure(figsize=(10,6))

plt.scatter(volatility, annual_returns)

for ticker in tickers:
    plt.text(volatility[ticker], annual_returns[ticker], ticker)

plt.xlabel("Risk (Volatility)")
plt.ylabel("Return")

plt.title("Risk vs Return Analysis")

plt.show()

# --- GET S&P500 TICKERS (ALTERNATIVE METHOD) ---

import requests
import pandas as pd

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

headers = {"User-Agent": "Mozilla/5.0"}

html = requests.get(url, headers=headers).text

tables = pd.read_html(html)

sp500_table = tables[0]

tickers = sp500_table["Symbol"].tolist()

print("Number of companies:", len(tickers))
print(tickers[:20])

# --- DOWNLOAD STOCK DATA FOR S&P500 ---

import yfinance as yf

sample_tickers = tickers[:50]

data = yf.download(sample_tickers, start="2018-01-01")["Close"]

print(data.head())

# --- CALCULATE RETURNS ---

returns = data.pct_change().dropna()

annual_returns = returns.mean() * 252
volatility = returns.std() * (252 ** 0.5)

print(annual_returns.head())

# --- SHARPE RATIO ANALYSIS ---

risk_free_rate = 0.02

sharpe = (annual_returns - risk_free_rate) / volatility

summary = pd.DataFrame()

summary["Return"] = annual_returns
summary["Volatility"] = volatility
summary["Sharpe"] = sharpe

print(summary.sort_values("Sharpe", ascending=False).head(10))

# --- TOP STOCKS VISUALIZATION ---

top_stocks = summary.sort_values("Sharpe", ascending=False).head(10)

plt.figure(figsize=(10,6))

plt.bar(top_stocks.index, top_stocks["Sharpe"])

plt.title("Top S&P500 Stocks by Sharpe Ratio")

plt.xticks(rotation=45)

plt.show()